package Vista;
import java.security.GUI;

import javax.swing.JOptionPane;

import Controlador.CandidatosControlador;
import Modelo.Candidatos;

public class Actualizar extends javax.swing.JPanel {

    /**
     * Creates new form Actualizar
     */
    public Actualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        buttonGroupOrientacion = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        labelPromesas = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        labelCedula = new javax.swing.JLabel();
        jComboBoxOrientacion = new javax.swing.JComboBox<>();
        labelCiudad = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        labelOrientacion = new javax.swing.JLabel();
        jComboBoxCedulas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelPartido = new javax.swing.JLabel();
        labelPromesas2 = new javax.swing.JLabel();
        labelPromesas3 = new javax.swing.JLabel();
        flecha1 = new javax.swing.JLabel();
        flecha2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jComboBoxCiudades = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPromesas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPromesas.setForeground(new java.awt.Color(22, 124, 214));
        labelPromesas.setText("Para agregar una promesa presiona Enter");
        jPanel2.add(labelPromesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        labelNombre.setBackground(new java.awt.Color(22, 22, 22));
        labelNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(51, 51, 51));
        labelNombre.setText("Nombre candidato:");
        jPanel2.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jTextField1.setBackground(new java.awt.Color(229, 229, 229));
        jTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(75, 75, 75));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 280, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 10));

        labelCedula.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(51, 51, 51));
        labelCedula.setText("Cedula candidato:");
        jPanel2.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBoxOrientacion.setBackground(new java.awt.Color(28, 30, 65));
        jComboBoxOrientacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxOrientacion.setForeground(new java.awt.Color(131, 190, 242));
        jComboBoxOrientacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una orientación politica para ver las opciones" }));
        jComboBoxOrientacion.setBorder(null);
        jPanel2.add(jComboBoxOrientacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 520, -1));

        labelCiudad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(51, 51, 51));
        labelCiudad.setText("Ciudad:");
        jPanel2.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        buttonGroupOrientacion.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(22, 124, 214));
        jRadioButton1.setText("Izquierda");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));
        buttonGroupOrientacion.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(22, 124, 214));
        jRadioButton2.setText("Derecha");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        labelOrientacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelOrientacion.setForeground(new java.awt.Color(51, 51, 51));
        labelOrientacion.setText("Orientacion Politica:");
        jPanel2.add(labelOrientacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jComboBoxCedulas.setBackground(new java.awt.Color(28, 30, 65));
        jComboBoxCedulas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxCedulas.setForeground(new java.awt.Color(102, 255, 102));
        jComboBoxCedulas.setModel(new javax.swing.DefaultComboBoxModel<>(CandidatosControlador.ObtenerCedulas(GUI.candidatos)));
        jComboBoxCedulas.setBorder(null);

        jComboBoxCedulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCedulasActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCedulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 310, -1));

        jTextArea1.setBackground(new java.awt.Color(28, 30, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 255, 102));
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 460, 110));

        labelPartido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPartido.setForeground(new java.awt.Color(51, 51, 51));
        labelPartido.setText("Partido Politico:");
        jPanel2.add(labelPartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        labelPromesas2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPromesas2.setForeground(new java.awt.Color(51, 51, 51));
        labelPromesas2.setText("(Cada renglon seria una promesa)");
        jPanel2.add(labelPromesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        labelPromesas3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPromesas3.setForeground(new java.awt.Color(51, 51, 51));
        labelPromesas3.setText("Ingrese la lista de promesas:");
        jPanel2.add(labelPromesas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        flecha1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        flecha1.setForeground(new java.awt.Color(51, 51, 51));
        flecha1.setText("->");
        jPanel2.add(flecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 20, -1));

        flecha2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        flecha2.setForeground(new java.awt.Color(51, 51, 51));
        flecha2.setText("->");
        jPanel2.add(flecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 20, 30));

        jButton1.setBackground(new java.awt.Color(22, 124, 214));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(229, 229, 229));
        jButton1.setText("Actualizar Candidato");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, -1, -1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(22, 124, 214));
        titulo.setText("Actualizar Candidato existente");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jComboBoxCiudades.setBackground(new java.awt.Color(28, 30, 65));
        jComboBoxCiudades.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxCiudades.setForeground(new java.awt.Color(131, 190, 242));
        jComboBoxCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cali", "Palmira", "Candelaria", "Dagua", "ElCerrito", "Florida", "Jamundi", "LaCumbre", "Pradera", "Vijes", "Yumbo", "tulua", "buga" }));
        jComboBoxCiudades.setBorder(null);
        jPanel2.add(jComboBoxCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>                        
    private void jComboBoxCedulasActionPerformed(java.awt.event.ActionEvent evt) {   
        String cedula = (String) jComboBoxCedulas.getSelectedItem();
        Candidatos candidato = CandidatosControlador.buscarCandidatosPorCedula(GUI.candidatos, cedula);
        if (candidato != null){
            String nombre = candidato.getNombre();
            String ciudad = candidato.getCiudad_origen();
            Boolean orientacion = candidato.getOrientacion_politica();
            String partido = candidato.getPartido_politico();
            String promesas = candidato.getLista_promesas();

            jTextField1.setText(nombre);
            jComboBoxCiudades.setSelectedItem(ciudad);
            if (orientacion){
                jRadioButton2ActionPerformed(evt);
                jRadioButton2.setSelected(true);
            }else{
                jRadioButton1ActionPerformed(evt);
                jRadioButton1.setSelected(true);
            }
            jComboBoxOrientacion.setSelectedItem(partido);
            jTextArea1.setText(promesas);

        }
    }
    private void jButton1ActionPerformed(java.awt.event. ActionEvent evt)
    {
        String Nombre = jTextField1.getText();
        String Cedula = (String) jComboBoxCedulas.getSelectedItem();
        String Ciudad = (String) jComboBoxCiudades.getSelectedItem(); 
        String Partido = (String) jComboBoxOrientacion.getSelectedItem();
        String Promesas = jTextArea1.getText();
        Boolean Orientacion;
        if(jRadioButton1.isSelected()){
            Orientacion = false;
        }else if(jRadioButton2.isSelected()){
            Orientacion = true;
        }else{Orientacion = false; } 

        if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false){
            JOptionPane.showMessageDialog(null,"No selecciono ninguna opción de Orientación");
        }
        else{
            if(jTextField1.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor rellena todos los datos (Cedula)", "Error ", JOptionPane.ERROR_MESSAGE); 
                }else{
                    Candidatos candidatonuevo  = new Candidatos(Nombre, Cedula, Ciudad, Orientacion, Partido, Promesas, 0);
                    GUI.Actualizar(candidatonuevo);
                    JOptionPane.showMessageDialog(null, "Usuario actualizado correctamente", "Actualizar Registro ", JOptionPane.INFORMATION_MESSAGE);
                }
        }  
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jComboBoxOrientacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido_de_la_U","Partido_Alianza_Verde","Partido_Polo_Democrático_Alternativo", "Colombia_Humana,Partido_Centro_Democrático,Movimiento_Alternativo_Indígena_y_Social","Partido_Colombia_Justa_Libres","Partido_Colombia_Renaciente","Partido_ADA","Partido_Dignidad_y_Compromiso" }));
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jComboBoxOrientacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido_Liberal_Colombiano", "Partido_Conservador_Colombiano",
            "Liga_de_Gobernantes_Anticorrupción","Movimiento_Autoridades_Indígenas_de_Colombia",
            "Partido_Verde_Oxígeno", "Unión_Patriótica", "Salvación_Nacional",
            "Partido_Alianza_Social_Independiente","Partido_Cambio_Radical", "Partido_Político_Mira" }));
    }                                             

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroupOrientacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxOrientacion;
    private javax.swing.JComboBox<String> jComboBoxCedulas;
    private javax.swing.JComboBox<String> jComboBoxCiudades;
    private javax.swing.JLabel labelPromesas;
    private javax.swing.JLabel flecha1;
    private javax.swing.JLabel flecha2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelOrientacion;
    private javax.swing.JLabel labelPartido;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel labelPromesas2;
    private javax.swing.JLabel labelPromesas3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}
