package Vista;
/* 
 * @author Anderson
 */

import java.awt.Color;
import java.security.GUI;

import javax.swing.JOptionPane;

import Controlador.CandidatosControlador;

public class Borrar extends javax.swing.JPanel {

    /**
     * Creates new form Borrar
     */
    public Borrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelBorrar = new javax.swing.JLabel();
        jComboBoxCedulas = new javax.swing.JComboBox<>();
        jButtonBorrar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBorrar.setBackground(new java.awt.Color(22, 22, 22));
        labelBorrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelBorrar.setForeground(new java.awt.Color(51, 51, 51));
        labelBorrar.setText("Elige el candidato que deseas borrar:");
        jPanel2.add(labelBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jComboBoxCedulas.setBackground(Color.white);
        jComboBoxCedulas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxCedulas.setForeground(new java.awt.Color(131, 190, 242));
        jComboBoxCedulas.setModel(new javax.swing.DefaultComboBoxModel<>(CandidatosControlador.ObtenerCedulas(GUI.candidatos)));
        jComboBoxCedulas.setBorder(null);
        jComboBoxCedulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCedulasActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxCedulas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 760, -1));

        jButtonBorrar.setBackground(new java.awt.Color(22, 124, 214));
        jButtonBorrar.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(229, 229, 229));
        jButtonBorrar.setText("Borrar candidato");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(22, 124, 214));
        titulo.setText("Borrar candidato existente");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>                        

    private void jComboBoxCedulasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String Cedula = (String) jComboBoxCedulas.getSelectedItem();
        CandidatosControlador.borrarPorCedula(Cedula,GUI.candidatos);
        JOptionPane.showMessageDialog(null, "Usuario borrado correctamente", "Borrar Registro ", JOptionPane.INFORMATION_MESSAGE);
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JComboBox<String> jComboBoxCedulas;
    private javax.swing.JLabel labelBorrar;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}