package Vista;

import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import Model.Candidatos;
import Model.*;


public class Insertar extends javax.swing.JPanel {

    /**
     * Creates new form Insertar
     */
    public Insertar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroupOrientacion = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelPromesa = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        TextCedula = new javax.swing.JTextField();
        TextNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        labelCedula = new javax.swing.JLabel();
        jComboBoxPartidos = new javax.swing.JComboBox<>();
        labelCiudad = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        labelOrientacion = new javax.swing.JLabel();
        jComboBoxCiudades = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelPartidos = new javax.swing.JLabel();
        labelpromesas2 = new javax.swing.JLabel();
        labelpromesas = new javax.swing.JLabel();
        jflecha = new javax.swing.JLabel();
        jflecha2 = new javax.swing.JLabel();
        crearCandidato = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPromesa.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPromesa.setForeground(new java.awt.Color(22, 124, 214));
        labelPromesa.setText("Para agregar una promesa presiona Enter");
        jPanel1.add(labelPromesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        labelNombre.setBackground(new java.awt.Color(22, 22, 22));
        labelNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(51, 51, 51));
        labelNombre.setText("Nombre candidato:");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        TextCedula.setBackground(new java.awt.Color(229, 229, 229));
        TextCedula.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextCedula.setForeground(new java.awt.Color(75, 75, 75));
        TextCedula.setBorder(null);
        TextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(TextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 280, -1));

        TextNombre.setBackground(new java.awt.Color(229, 229, 229));
        TextNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        TextNombre.setForeground(new java.awt.Color(75, 75, 75));
        TextNombre.setBorder(null);
        jPanel1.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 280, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 137, 300, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 10));

        labelCedula.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(51, 51, 51));
        labelCedula.setText("Cedula candidato:");
        jPanel1.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jComboBoxPartidos.setBackground(new java.awt.Color(28, 30, 65));
        jComboBoxPartidos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxPartidos.setForeground(new java.awt.Color(131, 190, 242));
        jComboBoxPartidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una orientación politica para ver las opciones" }));
        jComboBoxPartidos.setBorder(null);
        jPanel1.add(jComboBoxPartidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 520, -1));

        labelCiudad.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelCiudad.setForeground(new java.awt.Color(51, 51, 51));
        labelCiudad.setText("Ciudad:");
        jPanel1.add(labelCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        buttonGroupOrientacion.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(22, 124, 214));
        jRadioButton1.setText("Izquierda");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        buttonGroupOrientacion.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(22, 124, 214));
        jRadioButton2.setText("Derecha");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        labelOrientacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelOrientacion.setForeground(new java.awt.Color(51, 51, 51));
        labelOrientacion.setText("Orientacion Politica:");
        jPanel1.add(labelOrientacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jComboBoxCiudades.setBackground(new java.awt.Color(28, 30, 65));
        jComboBoxCiudades.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBoxCiudades.setForeground(new java.awt.Color(131, 190, 242));
        jComboBoxCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cali", "Palmira", "Candelaria", "Dagua", "ElCerrito", "Florida", "Jamundi", "LaCumbre", "Pradera", "Vijes", "Yumbo", "tulua", "buga" }));
        jComboBoxCiudades.setBorder(null);
        jPanel1.add(jComboBoxCiudades, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 310, -1));

        jTextArea1.setBackground(new java.awt.Color(28, 30, 65));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(51, 255, 102));
        jTextArea1.setRows(1);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 460, 110));

        labelPartidos.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelPartidos.setForeground(new java.awt.Color(51, 51, 51));
        labelPartidos.setText("Partido Politico:");
        jPanel1.add(labelPartidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        labelpromesas2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelpromesas2.setForeground(new java.awt.Color(51, 51, 51));
        labelpromesas2.setText("(Cada renglon seria una promesa)");
        jPanel1.add(labelpromesas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, -1, -1));

        labelpromesas.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelpromesas.setForeground(new java.awt.Color(51, 51, 51));
        labelpromesas.setText("Ingrese la lista de promesas:");
        jPanel1.add(labelpromesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jflecha.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jflecha.setForeground(new java.awt.Color(51, 51, 51));
        jflecha.setText("->");
        jPanel1.add(jflecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 20, -1));

        jflecha2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jflecha2.setForeground(new java.awt.Color(51, 51, 51));
        jflecha2.setText("->");
        jPanel1.add(jflecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 20, 30));

        crearCandidato.setBackground(new java.awt.Color(22, 124, 214));
        crearCandidato.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        crearCandidato.setForeground(new java.awt.Color(229, 229, 229));
        crearCandidato.setText("Crear Candidato Nuevo");

        crearCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCandidatoActionPerformed(evt);
            }
        });

        jPanel1.add(crearCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, -1, -1));
        titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(22, 124, 214));
        titulo.setText("Insertar Candidato nuevo");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 823, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void TextCedulaActionPerformed(java.awt.event.ActionEvent evt) {                                            
    }                                           
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jComboBoxPartidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido_de_la_U","Partido_Alianza_Verde","Partido_Polo_Democrático_Alternativo", "Colombia_Humana,Partido_Centro_Democrático,Movimiento_Alternativo_Indígena_y_Social","Partido_Colombia_Justa_Libres","Partido_Colombia_Renaciente","Partido_ADA","Partido_Dignidad_y_Compromiso" }));

    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        jComboBoxPartidos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partido_Liberal_Colombiano", "Partido_Conservador_Colombiano",
            "Liga_de_Gobernantes_Anticorrupción","Movimiento_Autoridades_Indígenas_de_Colombia",
            "Partido_Verde_Oxígeno", "Unión_Patriótica", "Salvación_Nacional",
            "Partido_Alianza_Social_Independiente","Partido_Cambio_Radical", "Partido_Político_Mira" }));
    }   
    private void crearCandidatoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String Nombre = TextNombre.getText();
        String Cedula = TextCedula.getText();
        String Ciudad = (String) jComboBoxCiudades.getSelectedItem();
        String Partido = (String) jComboBoxPartidos.getSelectedItem();
        String Promesas = jTextArea1.getText();
        Boolean Orientacion;
        if(jRadioButton1.isSelected()){
            Orientacion = false;
        }
        else if(jRadioButton2.isSelected()){
            Orientacion = true;
        }else{
            Orientacion = false;
        } 
        
        if(jRadioButton1.isSelected()==false && jRadioButton2.isSelected()==false){
            JOptionPane.showMessageDialog(null,"No selecciono ninguna opción de Orientación");
        }else{
            if(TextNombre.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor rellena todos los datos (Nombre)", "Error ", JOptionPane.ERROR_MESSAGE);     
            }else if(TextCedula.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Por favor rellena todos los datos (Cedula)", "Error ", JOptionPane.ERROR_MESSAGE); 
                }else{
                    Modelo.Candidatos candidatonuevo  = new Modelo.Candidatos(Nombre, Cedula, Ciudad, Orientacion, Partido, Promesas, 0);
                    GUI.candidatos.add(candidatonuevo);
                    JOptionPane.showMessageDialog(null, "Usuario creado correctamente", "Nuevo Registro ", JOptionPane.INFORMATION_MESSAGE);
                }
        }  
    }                                             
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroupOrientacion;
    private javax.swing.JButton crearCandidato;
    private javax.swing.JComboBox<String> jComboBoxPartidos;
    private javax.swing.JComboBox<String> jComboBoxCiudades;
    private javax.swing.JLabel labelPromesa;
    private javax.swing.JLabel jflecha;
    private javax.swing.JLabel jflecha2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JLabel labelCiudad;
    private javax.swing.JLabel labelOrientacion;
    private javax.swing.JLabel labelPartidos;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel labelpromesas2;
    private javax.swing.JLabel labelpromesas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField TextCedula;
    private javax.swing.JTextField TextNombre;
    // End of variables declaration                   
}
