package Vista;
import javax.swing.table.DefaultTableModel;

import Modelo.Candidatos;

public class Listar extends javax.swing.JPanel {

    /**
     * Creates new form Listar
     */
    public Listar() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modelo =new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Cedula", "Nombre", "Ciudad", "Orientacion Politica", "Partido Politico", "Promesas de Campaña"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        };
        jTable1.setModel(modelo);
        for (Candidatos candi: GUI.candidatos){
            agregarCandidatoATabla(candi);
        }
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 660, 420));

        titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(22, 124, 214));
        titulo.setText("Listar Candidatos");
        jPanel2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
        );
        
        

    }// </editor-fold>         
                   
    private void agregarCandidatoATabla(Candidatos candidato) {
        String Orientacion = "";
        if(candidato.getOrientacion_politica()){
            Orientacion = "Derecha";
        }else Orientacion = "izquierda";

            Object[] fila = {
                candidato.getCedula(),
                candidato.getNombre(),
                candidato.getCiudad_origen(),
                Orientacion,
                candidato.getPartido_politico(),
                candidato.getLista_promesas()
            };
        
            // Agregar la nueva fila al modelo de la tabla
            modelo.addRow(fila);
    }
    // Variables declaration - do not modify                     
    private DefaultTableModel modelo;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
